#!/usr/bin/env python3
"""Mirror every runtime network dependency into the repository.

LAYERS must render identically offline: the UI is measured in Inter / JetBrains
Mono / Michroma metrics, and the runtime needs the React UMD globals before
support.js boots. Both are vendored here so `npm run dev` makes zero external
requests.

Run from the repository root:

    python scripts/vendor-assets.py

Outputs:
    fonts/*.woff2      subsetted faces, byte-identical to what fonts.gstatic.com
                       serves for the queries below
    fonts/fonts.css    the editor's own faces (Inter / JetBrains Mono / Michroma),
                       generated from the Google Fonts css2 response with the URLs
                       rewritten to the local files; unicode-range blocks preserved
    fonts/projects.css the faces the loaded projects ask for and the editor does
                       not already carry. A project's layers.json may name a
                       fonts.googleapis.com URL; the loader never fetches it, it
                       resolves the family against this sheet instead
    vendor/*.js        React + ReactDOM UMD, verified against the SRI hashes that
                       support.js declares, so the local copies provably match what
                       the app loaded from the CDN

Both outputs are committed. Re-run only to refresh a pinned version, and review
the resulting diff: a changed .woff2 means Google reissued the face and the
rendering may shift.
"""

import base64
import hashlib
import os
import re
import sys
import urllib.request

# Chrome UA — Google Fonts serves woff2 only to browsers that advertise support.
UA = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"
)

# (css2 query, output sheet, description for the generated header).
# The editor set is frozen: changing it reissues every .woff2 and shifts the UI
# metrics. Project faces go in the second sheet so the two never interfere.
FONT_SETS = [
    (
        "https://fonts.googleapis.com/css2"
        "?family=Inter:wght@400;500;600;700"
        "&family=JetBrains+Mono:wght@400;500;700"
        "&family=Michroma"
        "&display=swap",
        "fonts/fonts.css",
        "Inter:wght@400;500;600;700 + JetBrains Mono:wght@400;500;700 + Michroma, display=swap",
    ),
    (
        # Asked for by the target projects. Axai names all three in its
        # wwwroot/index.html; JetBrains Mono 600 is the one weight the editor
        # sheet above does not carry, and a second @font-face extends the family
        # rather than competing with it.
        "https://fonts.googleapis.com/css2"
        "?family=Newsreader:ital,opsz,wght@0,6..72,400;0,6..72,500;0,6..72,600"
        ";1,6..72,400;1,6..72,500;1,6..72,600"
        "&family=Geist:wght@400;500;600;700"
        "&family=JetBrains+Mono:wght@600"
        "&display=swap",
        "fonts/projects.css",
        "Newsreader (ital, opsz 6..72, wght 400;500;600) + Geist:wght@400;500;600;700"
        " + JetBrains Mono:wght@600, display=swap",
    ),
]

# URL and expected SRI copied from support.js (REACT_URL / REACT_SRI et al).
# support.js is generated and must not be edited, so these stay in sync by hand.
REACT_UMD = [
    (
        "https://unpkg.com/react@18.3.1/umd/react.production.min.js",
        "sha384-DGyLxAyjq0f9SPpVevD6IgztCFlnMF6oW/XQGmfe+IsZ8TqEiDrcHkMLKI6fiB/Z",
        "vendor/react.production.min.js",
    ),
    (
        "https://unpkg.com/react-dom@18.3.1/umd/react-dom.production.min.js",
        "sha384-gTGxhz21lVGYNMcdJOyq01Edg0jhn/c22nsx0kyqP0TxaV5WVdsSH1fSDUf5YJj1",
        "vendor/react-dom.production.min.js",
    ),
]

HEADER = (
    "/* GENERATED by scripts/vendor-assets.py from the Google Fonts css2 response for:\n"
    " *   {desc}\n"
    " * Byte-identical faces mirrored into this folder.\n"
    " * Do not hand-edit: unicode-range subsetting must match Google's output exactly. */\n\n"
)


def fetch(url: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    return urllib.request.urlopen(req, timeout=60).read()


def vendor_fonts(query: str, out_css: str, desc: str) -> None:
    css = fetch(query).decode("utf-8")
    urls = sorted(set(re.findall(r"https://fonts\.gstatic\.com/[^)]+", css)))
    if not urls:
        sys.exit("no font URLs in the css2 response — check the query or the UA")
    os.makedirs("fonts", exist_ok=True)

    for url in urls:
        family = url.split("/s/")[1].split("/")[0]
        # Hash of the source URL keeps the local name stable across re-runs and
        # distinguishes the subsets, which share a family and differ only by range.
        name = f"{family}-{hashlib.sha1(url.encode()).hexdigest()[:8]}.woff2"
        data = fetch(url)
        with open(os.path.join("fonts", name), "wb") as fh:
            fh.write(data)
        css = css.replace(url, f"./{name}")
        print(f"  {len(data):>7}  fonts/{name}")

    with open(out_css, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(HEADER.format(desc=desc) + css)
    print(f"  {out_css} — {len(urls)} files, {css.count('@font-face')} @font-face blocks")


def vendor_react() -> None:
    os.makedirs("vendor", exist_ok=True)
    failed = False
    for url, expected, dest in REACT_UMD:
        data = fetch(url)
        actual = "sha384-" + base64.b64encode(hashlib.sha384(data).digest()).decode()
        with open(dest, "wb") as fh:
            fh.write(data)
        if actual == expected:
            print(f"  {len(data):>7}  {dest}  SRI match")
        else:
            failed = True
            print(f"  {len(data):>7}  {dest}  SRI MISMATCH")
            print(f"            expected {expected}")
            print(f"            actual   {actual}")
    if failed:
        sys.exit(
            "SRI mismatch: the CDN no longer serves the bytes support.js expects. "
            "Do not commit — investigate first."
        )


if __name__ == "__main__":
    if not os.path.isfile("index.html"):
        sys.exit("run this from the repository root")
    for query, out_css, desc in FONT_SETS:
        print(f"fonts -> {out_css}:")
        vendor_fonts(query, out_css, desc)
    print("react:")
    vendor_react()
    print("done — index.html should reference ./fonts/fonts.css and ./vendor/*.js")
